"""Generate a `HERMES.md` next to every package.

These are GENERATED, from `fleet.yaml` plus the live disk. That is the whole
point: a hand-written "where is this installed" note is wrong the first time
anyone changes anything, and nobody ever goes back to fix it. This way the
answer is regenerated from the same manifest that does the installing, so the
document and the machine cannot disagree.

The prose that needs judgment — why a package is on one profile and not
another, what bit someone last time — lives in the manifest's `notes:` field and
is carried through verbatim. Write it there, not here.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List

from . import sync
from .manifest import Manifest, Package

BANNER = """<!-- GENERATED by `fleet docs` from fleet.yaml — do not edit by hand.
     Prose belongs in that package's `notes:` field in fleet.yaml, which is
     reproduced verbatim below. Regenerate with: fleet docs --apply -->
"""

KIND_BLURB = {
    "agent-plugin": "Agent plugin — loaded by the Hermes agent, per profile.",
    "desktop-plugin": "Desktop plugin — extends the Hermes Desktop app. GLOBAL, installed once.",
    "skill": "Skill — a SKILL.md the model reads. Per profile, and paid for on every turn.",
    "skill-pack": "Skill pack — several skills at once. Per profile; watch the context cost.",
    "skin-pack": "Skin pack — CLI/TUI palettes. Per profile, inert until `display.skin` picks one.",
    "claude-skill": "Claude Code skill — installed into ~/.claude/skills, not into Hermes.",
    "mcp-server": "MCP server — registered under `mcp_servers` in each profile's config.yaml.",
    "python-package": "Python package — editable install into the Hermes venv, once.",
    "external": "External — this package owns its own installer. Fleet reports it and defers.",
}


def _render(pkg: Package, manifest: Manifest, actions: List[sync.Action]) -> str:
    lines: List[str] = [BANNER, f"# {pkg.name}", ""]

    if pkg.summary:
        lines += [pkg.summary, ""]
    if pkg.upstream:
        lines += [f"Upstream: {pkg.upstream}", ""]

    # ── where it lives ──
    lines += ["## Where it is installed", ""]
    if pkg.is_global:
        lines += [
            "**Global.** This package installs once for the whole machine, not per",
            "profile. Desktop plugins work this way by design: the app migrates any",
            "profile-scoped copy up into `~/.hermes/desktop-plugins/`, because a pane",
            "that vanished when you switched profiles read as a bug.",
            "",
        ]
    else:
        scope = ", ".join(f"`{p}`" for p in pkg.profiles) or "— none declared —"
        lines += [f"Profiles: {scope}", ""]
        missing = [n for n in manifest.profiles if n not in pkg.profiles]
        if missing:
            lines += [
                f"Deliberately NOT on: {', '.join(f'`{n}`' for n in missing)}. "
                "That is a tiering decision, not an oversight —",
                "see the note below and `fleet.yaml`.",
                "",
            ]

    lines += ["| surface | where it lands | how |", "|---|---|---|"]
    for action in actions:
        where = action.profile or "global"
        lines.append(f"| `{action.kind}` | `{action.target}` ({where}) | {action.mode} |")
    if not actions:
        lines.append("| — | nothing resolved; check `fleet status -v` | — |")
    lines.append("")

    kinds = sorted({s.kind for s in pkg.surfaces})
    lines += ["Surface kinds in play:", ""]
    lines += [f"- **`{k}`** — {KIND_BLURB.get(k, 'see FLEET.md')}" for k in kinds]
    lines.append("")

    # ── current state ──
    lines += ["## Current state", ""]
    worst = {a.verdict for a in actions}
    if worst <= {sync.OK}:
        lines += ["In sync with `fleet.yaml`.", ""]
    else:
        lines += ["| where | verdict | detail |", "|---|---|---|"]
        for action in actions:
            if action.verdict == sync.OK:
                continue
            lines.append(f"| {action.profile or 'global'} | `{action.verdict}` | {action.detail} |")
        lines.append("")

    # ── operating it ──
    lines += ["## Operating it", "", "```bash"]
    lines += [f"fleet status -v                 # includes this package"]
    lines += [f"fleet sync -k {pkg.name}{' ' * max(0, 18 - len(pkg.name))}# dry run, this package only"]
    lines += [f"fleet sync -k {pkg.name} --apply"]
    if any(s.kind == "agent-plugin" for s in pkg.surfaces):
        lines += [
            f"fleet enable {pkg.name} --apply   # add to plugins.enabled in each profile",
            f"fleet disable {pkg.name} --apply",
            "hermes gateway restart          # required after an enable/disable",
        ]
    lines += ["```", ""]

    # ── undo ──
    lines += ["## Removing it", "", "Take it out of `fleet.yaml`, then:", "", "```bash"]
    if any(s.kind == "agent-plugin" for s in pkg.surfaces):
        lines.append(f"fleet disable {pkg.name} --apply")
    for action in actions:
        lines.append(f"rm -rf '{action.target}'" if action.mode != "mirror" else f"# skins: remove the files fleet mirrored into {action.target}")
    lines += ["```", ""]
    if any(a.mode in ("symlink", "link", "junction") for a in actions):
        lines += [
            "> Those targets are links back into this checkout. Removing a link removes",
            "> the link, never the source — but use `rm -rf` on the link itself, not on",
            "> anything *inside* it, or you will delete the real files through it.",
            "",
        ]

    if pkg.notes:
        lines += ["## Notes", "", pkg.notes, ""]

    lines += [
        "---",
        "",
        f"Generated {datetime.now().strftime('%Y-%m-%d')} from `fleet.yaml`. "
        "See [FLEET.md](../FLEET.md) for the model.",
        "",
    ]
    return "\n".join(lines)


def generate(manifest: Manifest, *, apply: bool = False) -> List[tuple]:
    """Write a HERMES.md into each package's source directory.

    Several manifest packages can share one source directory — `hermes-bot-kit`
    is both `bot-kit-agent` (per profile) and `bot-kit-desktop` (global),
    because that is genuinely what the repo contains. Writing per package would
    make the second silently clobber the first, so entries are grouped by
    directory and rendered into one document.

    Returns (package, path, wrote) tuples. Packages with no source directory in
    this repo (upstream-managed ones) are skipped — we have nowhere to put the
    file and no business writing into someone else's checkout.
    """
    plan = sync.plan(manifest)
    by_package: dict = {}
    for action in plan.actions:
        by_package.setdefault(action.package, []).append(action)

    grouped: dict = {}
    results = []
    for pkg in manifest.packages:
        if pkg.source is None or not pkg.source.is_dir():
            results.append((pkg.name, None, False))
            continue
        grouped.setdefault(pkg.source.resolve(), []).append(pkg)

    for source, packages in grouped.items():
        target = source / "HERMES.md"
        sections = [_render(p, manifest, by_package.get(p.name, [])) for p in packages]
        if len(sections) > 1:
            intro = (
                f"{BANNER}# {source.name}\n\n"
                f"This directory provides {len(sections)} fleet packages, documented in turn:\n\n"
                + "\n".join(f"- **{p.name}** — {p.summary.splitlines()[0] if p.summary else ''}" for p in packages)
                + "\n\n---\n\n"
            )
            # Strip each section's own banner; the grouped document has one.
            text = intro + "\n\n---\n\n".join(s.replace(BANNER, "", 1).lstrip() for s in sections)
        else:
            text = sections[0]

        changed = not target.is_file() or target.read_text(encoding="utf-8") != text
        if apply and changed:
            target.write_text(text, encoding="utf-8")
        for pkg in packages:
            results.append((pkg.name, target, changed))
    return results
