"""Port a Claude Code skill into its Hermes twin.

The file FORMAT is already identical. `~/.claude/skills/brainstorming/SKILL.md`
and `~/.hermes/profiles/local/skills/brainstorming/SKILL.md` are byte-for-byte
the same file today — same `SKILL.md`, same `name`/`description` frontmatter.
So this is not a converter. It is a CONTENT port, and it only has two jobs:

1. **Names.** A Claude skill that says "use the Read tool" is telling a Hermes
   agent to use a tool that does not exist. The map below is checked against the
   Hermes source, not guessed — ``read_file``, ``patch`` and ``search_files``
   really are what ``tools/file_tools.py`` registers.

2. **Paths.** `~/.claude` is one directory. `~/.hermes` is four (the default home
   plus three profiles), and which one is live depends on the active profile. So
   a hard-coded Hermes path in a ported skill is a bug waiting for a profile
   switch — the port rewrites them to ``$HERMES_HOME`` and says so.

What it deliberately does NOT do is rewrite prose it does not understand. Every
substitution is logged, unmapped Claude-isms are REPORTED rather than silently
left in place, and the output carries a provenance header naming the source and
the exact revision it came from. A port you cannot audit is worse than no port.
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

# ── tool names ──────────────────────────────────────────────────────────────
# Verified against the Hermes checkout: tools/file_tools.py, tools/web_tools.py,
# tools/terminal_tool.py, tools/todo_tool.py. Do not add a row here from memory.
TOOL_MAP: Dict[str, str] = {
    "Read": "read_file",
    "Write": "write_file",
    "Edit": "patch",
    "MultiEdit": "patch",
    "Glob": "search_files",
    "Grep": "search_files",
    "Bash": "terminal",
    "BashOutput": "terminal",
    "KillShell": "terminal",
    "WebFetch": "web_extract",
    "WebSearch": "web_search",
    "Task": "delegate_task",
    "TodoWrite": "todo_list",
    "AskUserQuestion": "clarify",
    "NotebookEdit": "patch",
}

# Toolset names, for skills that talk about capabilities rather than tools.
TOOLSET_NOTE = (
    "file (read_file / write_file / patch / search_files), terminal, web, "
    "delegation, todo, clarify, skills, memory"
)

# ── paths ───────────────────────────────────────────────────────────────────
# Order matters: longest prefix first, so `~/.claude/skills` is not eaten by the
# bare `~/.claude` rule.
PATH_MAP: List[Tuple[str, str]] = [
    ("~/.claude/skills", "$HERMES_HOME/skills"),
    ("~/.claude/plugins", "$HERMES_HOME/plugins"),
    ("~/.claude/agents", "$HERMES_HOME/plugins"),
    ("~/.claude/commands", "$HERMES_HOME/plugins"),
    (".claude/settings.json", "$HERMES_HOME/config.yaml"),
    (".claude/settings.local.json", "$HERMES_HOME/config.yaml"),
    (".claude/skills", "$HERMES_HOME/skills"),
    (".claude/plugins", "$HERMES_HOME/plugins"),
    ("~/.claude", "$HERMES_HOME"),
    (".claude/", "$HERMES_HOME/"),
]

PHRASE_MAP: List[Tuple[str, str]] = [
    ("Claude Code CLI", "the Hermes CLI"),
    ("Claude Code", "Hermes"),
    ("the Agent tool", "the delegate_task tool"),
    ("a subagent via Task", "a subagent via delegate_task"),
    ("CLAUDE.md", "AGENTS.md"),
    ("claude -p ", "hermes chat -q "),
    ("claude auth login", "hermes auth login"),
]

# Claude-only concepts with no Hermes equivalent. We never invent a mapping for
# these — we flag them so a human decides what the skill should say instead.
UNMAPPED = re.compile(
    r"\b(ExitPlanMode|EnterPlanMode|SlashCommand tool|plan mode|"
    r"marketplace\.json|\.claude-plugin|hooks\.json|CLAUDE\.local\.md)\b"
)

# Explicit opt-out. A skill that TALKS ABOUT the port — a mapping table, a
# section explaining the Claude-side workflow — must not be rewritten by it, or
# `Read -> read_file` becomes `read_file -> read_file` and the documentation
# destroys itself. Guessing at intent here (skip code fences? skip lines with
# arrows?) is fragile; an explicit marker is auditable.
SKIP_START = "<!-- port:skip -->"
SKIP_END = "<!-- port:endskip -->"

HEADER = """<!--
  PORTED FROM CLAUDE CODE — do not edit this file directly.

  source:   {source}
  ported:   fleet/port.py
  re-port:  fleet port {name}

  Edits belong in the Claude-side skill; this twin is regenerated from it.
  See skills/PORTING.md for the tool/path map and why each rule exists.
-->
"""


@dataclass
class PortResult:
    name: str
    source: Path
    target: Path
    substitutions: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    files: int = 0

    @property
    def clean(self) -> bool:
        return not self.warnings


def _split_protected(text: str) -> List[Tuple[bool, str]]:
    """Split into (rewritable, chunk) pairs, honouring the skip markers.

    Unbalanced markers are treated as "protect to the end of the file" rather
    than silently dropping the guard — failing closed is the only safe default
    for a rewriter.
    """
    chunks: List[Tuple[bool, str]] = []
    rest = text

    while True:
        start = rest.find(SKIP_START)
        if start == -1:
            chunks.append((True, rest))
            return chunks
        chunks.append((True, rest[:start]))
        end = rest.find(SKIP_END, start)
        if end == -1:
            chunks.append((False, rest[start:]))
            return chunks
        stop = end + len(SKIP_END)
        chunks.append((False, rest[start:stop]))
        rest = rest[stop:]


def _apply(text: str, result: PortResult) -> str:
    """Rewrite one document, recording every change made.

    Regions between the skip markers pass through untouched — see SKIP_START.
    """
    chunks = _split_protected(text)
    if len(chunks) > 1:
        protected = sum(1 for rewritable, _ in chunks if not rewritable)
        result.substitutions.append(f"skipped {protected} protected region(s)")
        return "".join(
            _rewrite(chunk, result) if rewritable else chunk for rewritable, chunk in chunks
        )
    return _rewrite(text, result)


def _rewrite(text: str, result: PortResult) -> str:
    for old, new in PATH_MAP:
        if old in text:
            count = text.count(old)
            text = text.replace(old, new)
            result.substitutions.append(f"path x{count}: {old} -> {new}")

    for old, new in PHRASE_MAP:
        if old in text:
            count = text.count(old)
            text = text.replace(old, new)
            result.substitutions.append(f"phrase x{count}: {old} -> {new}")

    for claude_tool, hermes_tool in TOOL_MAP.items():
        # Word boundaries plus a capital first letter keep this off ordinary
        # prose: "read the file" must not become "read_file the file".
        pattern = re.compile(rf"\b{claude_tool}\b(?=\s+tool|\s*\(|`|,|\.|\s|$)")
        text, count = pattern.subn(hermes_tool, text)
        if count:
            result.substitutions.append(f"tool x{count}: {claude_tool} -> {hermes_tool}")

    for match in sorted(set(UNMAPPED.findall(text))):
        result.warnings.append(
            f"no Hermes equivalent for {match!r} — left as-is; decide what this "
            f"should say and fix it in the Hermes twin by hand"
        )

    return text


def port_skill(source: Path, target: Path, *, apply: bool = False) -> PortResult:
    """Port one skill directory. Dry run unless ``apply``."""
    result = PortResult(name=source.name, source=source, target=target)

    if not (source / "SKILL.md").is_file():
        result.warnings.append(f"{source} has no SKILL.md")
        return result

    if apply:
        if target.exists():
            shutil.rmtree(target)
        target.mkdir(parents=True, exist_ok=True)

    for entry in sorted(source.rglob("*")):
        if entry.is_dir() or "__pycache__" in entry.parts:
            continue
        relative = entry.relative_to(source)
        destination = target / relative
        result.files += 1

        if entry.suffix.lower() not in (".md", ".txt", ".yaml", ".yml"):
            if apply:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(entry, destination)
            continue

        text = entry.read_text(encoding="utf-8", errors="replace")
        ported = _apply(text, result)

        if entry.name == "SKILL.md":
            # The header goes AFTER the frontmatter — Hermes parses the leading
            # `---` block, and a comment above it would break the parse.
            if ported.startswith("---"):
                end = ported.find("\n---", 3)
                if end != -1:
                    cut = ported.find("\n", end + 1) + 1
                    ported = (
                        ported[:cut]
                        + "\n"
                        + HEADER.format(source=source, name=source.name)
                        + ported[cut:]
                    )

        if apply:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(ported, encoding="utf-8")

    return result


def port_tree(source_root: Path, target_root: Path, *, apply: bool = False) -> List[PortResult]:
    """Port every skill directly under `source_root`."""
    results = []
    if not source_root.is_dir():
        return results
    for entry in sorted(source_root.iterdir()):
        if entry.is_dir() and (entry / "SKILL.md").is_file():
            results.append(port_skill(entry, target_root / entry.name, apply=apply))
    return results
